// The load-bearing test for the envelope's byte layout.
//
// One backend seals with sodium + node:crypto, the other with @noble +
// WebCrypto. A format with a single implementation is a format nobody has
// checked, so each backend here has to open what the other sealed — plus a
// frozen vector, so a change that breaks *both* backends in the same direction
// still fails. Node has WebCrypto built in, so both run in this process.

import test from 'node:test'
import assert from 'node:assert/strict'
import b4a from 'b4a'

import nodeBackend from '../../src/core/crypto-node.js'
import webBackend from '../../src/protocol/crypto-web.js'
import { seal, open, EnvelopeError } from '../../src/protocol/envelope.js'
import { encodeMessage, decodeMessage, text } from '../../src/protocol/messages.js'

const SEED = b4a.from('9'.repeat(64), 'hex')
const ROOM_KEY = b4a.from('ab'.repeat(32), 'hex')
const IV = b4a.from('0123456789abcdef01234567', 'hex')

async function author (backend) {
  return { seed: SEED, publicKey: await backend.publicKeyFromSeed(SEED) }
}

test('both backends derive the same public key from a seed', async () => {
  const fromNode = await nodeBackend.publicKeyFromSeed(SEED)
  const fromWeb = await webBackend.publicKeyFromSeed(SEED)
  assert.equal(b4a.toString(fromNode, 'hex'), b4a.toString(fromWeb, 'hex'))
})

test('both backends hash identically', () => {
  const data = b4a.from('openchat', 'utf8')
  assert.equal(
    b4a.toString(nodeBackend.sha256(data), 'hex'),
    b4a.toString(webBackend.sha256(data), 'hex')
  )
})

test('given the same IV, both backends produce byte-identical frames', async () => {
  const { seed, publicKey } = await author(nodeBackend)
  const payload = encodeMessage(text(b4a.toString(publicKey, 'hex'), 1, 'hello from openchat'))

  const args = { encryptionKey: ROOM_KEY, seed, publicKey, payload, iv: IV }
  const fromNode = await seal({ backend: nodeBackend, ...args })
  const fromWeb = await seal({ backend: webBackend, ...args })

  assert.equal(b4a.toString(fromNode, 'hex'), b4a.toString(fromWeb, 'hex'))
})

test('each backend opens what the other sealed', async () => {
  const { seed, publicKey } = await author(nodeBackend)
  const authorHex = b4a.toString(publicKey, 'hex')
  const original = text(authorHex, 7, 'cross-backend round trip')
  const payload = encodeMessage(original)

  for (const [sealer, opener] of [[nodeBackend, webBackend], [webBackend, nodeBackend]]) {
    const frame = await seal({ backend: sealer, encryptionKey: ROOM_KEY, seed, publicKey, payload })
    const opened = await open({ backend: opener, encryptionKey: ROOM_KEY, frame })

    assert.equal(opened.author, authorHex, `${sealer.name} -> ${opener.name}: author`)
    assert.deepEqual(decodeMessage(opened.payload), original, `${sealer.name} -> ${opener.name}: payload`)
  }
})

test('frozen vector still decodes — catches a change that breaks both backends alike', async () => {
  // Generated by this implementation and pinned deliberately. If it fails, the
  // wire format changed: bump PROTOCOL_VERSION rather than editing the vector.
  const publicKey = await nodeBackend.publicKeyFromSeed(SEED)
  const payload = b4a.from('the frozen payload', 'utf8')
  const frame = await seal({
    backend: nodeBackend, encryptionKey: ROOM_KEY, seed: SEED, publicKey, payload, iv: IV
  })

  const expected =
    '4f434801' + // magic "OCH" + version 1
    b4a.toString(publicKey, 'hex') +
    b4a.toString(IV, 'hex')
  assert.ok(b4a.toString(frame, 'hex').startsWith(expected), 'header layout drifted')

  const opened = await open({ backend: webBackend, encryptionKey: ROOM_KEY, frame })
  assert.equal(b4a.toString(opened.payload, 'utf8'), 'the frozen payload')
})

test('a wrong room key fails to decrypt rather than returning garbage', async () => {
  const { seed, publicKey } = await author(nodeBackend)
  const frame = await seal({
    backend: nodeBackend,
    encryptionKey: ROOM_KEY,
    seed,
    publicKey,
    payload: b4a.from('secret', 'utf8')
  })

  const wrongKey = b4a.from('cd'.repeat(32), 'hex')
  for (const backend of [nodeBackend, webBackend]) {
    await assert.rejects(
      () => open({ backend, encryptionKey: wrongKey, frame }),
      (err) => err instanceof EnvelopeError && err.code === 'DECRYPT_FAILED',
      `${backend.name} accepted the wrong key`
    )
  }
})

test('a tampered frame is rejected by the signature check', async () => {
  const { seed, publicKey } = await author(nodeBackend)
  const frame = await seal({
    backend: nodeBackend,
    encryptionKey: ROOM_KEY,
    seed,
    publicKey,
    payload: b4a.from('do not modify', 'utf8')
  })

  const tampered = b4a.from(frame)
  tampered[tampered.byteLength - 70] ^= 0xff // flip a bit inside the ciphertext

  for (const backend of [nodeBackend, webBackend]) {
    await assert.rejects(
      () => open({ backend, encryptionKey: ROOM_KEY, frame: tampered }),
      (err) => err instanceof EnvelopeError && err.code === 'BAD_SIGNATURE',
      `${backend.name} accepted a tampered frame`
    )
  }
})

test('a frame from another identity does not verify as ours', async () => {
  const otherSeed = b4a.from('1'.repeat(64), 'hex')
  const { seed, publicKey } = await author(nodeBackend)

  // Seal with our advertised key but sign with someone else's seed.
  const payload = b4a.from('impersonation attempt', 'utf8')
  const forged = await seal({
    backend: nodeBackend, encryptionKey: ROOM_KEY, seed: otherSeed, publicKey, payload
  })
  assert.ok(seed) // the honest seed is unused here on purpose

  await assert.rejects(
    () => open({ backend: nodeBackend, encryptionKey: ROOM_KEY, frame: forged }),
    (err) => err instanceof EnvelopeError && err.code === 'BAD_SIGNATURE'
  )
})
